---
- name: Install apache webserver.
  package:
    name: "{{ package_name }}"
    state: present

- name: copy file to webserver.
  copy:
    dest: "/var/www/html"
    src: "index.html"

- name: Start webserver.
  service:
    name: "{{ package_name }}"
    state: started
